package com.parsernews.model;

public enum DealStage {
    INITIAL_ANNOUNCEMENT,
    OFFER_INCREASE,
    DEFINITIVE_AGREEMENT,
    SHAREHOLDER_APPROVAL,
    REGULATORY_APPROVAL,
    CLOSING_EXPECTED,
    COMPLETION_OR_CLOSED,
    LITIGATION_OR_LAW_FIRM_UPDATE,
    RUMOR_OR_EXPLORATION,
    UNKNOWN
}
