package com.parsernews.model;

public enum DealRelevance {
    PUBLIC_TAKE_PRIVATE,
    PUBLIC_CASH_ACQUISITION,
    PUBLIC_STOCK_MERGER,
    PUBLIC_PUBLIC_MERGER,
    REVERSE_TAKEOVER,
    PRIVATE_COMPANY_ACQUISITION,
    LAW_FIRM_OR_SHAREHOLDER_ALERT,
    NOT_TRADABLE,
    UNKNOWN
}
