package com.parsernews.model;

public enum EventType {
    TAKE_PRIVATE_CONFIRMED,
    TAKE_PRIVATE_RUMOR,
    CONFIRMED_DEAL,
    MERGER_CONFIRMED,
    ACQUISITION_CONFIRMED,
    ACQUISITION_RUMOR,
    TENDER_OFFER,
    DEBT_TENDER_OFFER,
    STRATEGIC_ALTERNATIVES,
    OFFERING_OR_DILUTION,
    BANKRUPTCY_RISK,
    NOISE,
    UNKNOWN
}
