spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/parsernews}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:parsernews}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:parsernews}
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.open-in-view=false
spring.flyway.enabled=true
spring.flyway.locations=classpath:db/migration
