spring.datasource.url=jdbc:postgresql://localhost:5432/parsernews
spring.datasource.username=parsernews
spring.datasource.password=parsernews
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.hibernate.ddl-auto=update
spring.jpa.open-in-view=false
