create table news_sources (
    id bigint generated by default as identity primary key,
    name varchar(255) not null,
    type varchar(255) not null,
    url varchar(2048),
    enabled boolean not null default true,
    created_at timestamp with time zone not null
);

alter table news_sources
    add constraint uk_news_sources_name unique (name);

create table news_articles (
    id bigint generated by default as identity primary key,
    source_id bigint not null,
    url_hash varchar(128) not null,
    ticker varchar(32),
    company_name varchar(255),
    headline varchar(2048) not null,
    article_text varchar(10000),
    url varchar(2048) not null,
    published_at timestamp with time zone,
    collected_at timestamp with time zone not null
);

alter table news_articles
    add constraint uk_news_articles_url_hash unique (url_hash);

alter table news_articles
    add constraint fk_news_articles_source
    foreign key (source_id) references news_sources (id);

create index idx_news_articles_collected_at
    on news_articles (collected_at desc);

create table detected_events (
    id bigint generated by default as identity primary key,
    article_id bigint not null,
    event_type varchar(64) not null,
    review_status varchar(64) not null,
    validation_status varchar(64),
    confidence_score integer not null,
    target_company varchar(255),
    target_ticker varchar(32),
    acquirer varchar(255),
    offer_price varchar(255),
    transaction_value varchar(255),
    cash_or_stock varchar(255),
    premium_percent varchar(255),
    candidate_score integer default 0,
    candidate_strength varchar(32),
    candidate_reason varchar(1024),
    alert_eligible boolean default false,
    alert_queued_at timestamp with time zone,
    alert_reason varchar(1024),
    manual_review_status varchar(32),
    manual_review_reason varchar(64),
    manual_review_note varchar(2048),
    manual_reviewed_at timestamp with time zone,
    matched_positive_keywords varchar(2048),
    matched_negative_keywords varchar(2048),
    false_positive_reasons varchar(2048),
    explanation varchar(4096),
    review_notes varchar(2048),
    detected_at timestamp with time zone not null
);

alter table detected_events
    add constraint uk_detected_events_article unique (article_id);

alter table detected_events
    add constraint fk_detected_events_article
    foreign key (article_id) references news_articles (id);

create index idx_detected_events_detected_at
    on detected_events (detected_at desc);

create index idx_detected_events_candidate_strength
    on detected_events (candidate_strength);

create index idx_detected_events_manual_review
    on detected_events (manual_review_status, manual_review_reason);

create table scan_runs (
    id bigint generated by default as identity primary key,
    started_at timestamp with time zone not null,
    finished_at timestamp with time zone,
    trigger_type varchar(32) not null,
    status varchar(32) not null,
    total_fetched integer not null default 0,
    candidates_found integer not null default 0,
    saved_articles integer not null default 0,
    duplicates_skipped integer not null default 0,
    errors_count integer not null default 0,
    error_message varchar(2048)
);

create index idx_scan_runs_started_at
    on scan_runs (started_at desc);
