create table sec_filings (
    id bigint generated by default as identity primary key,
    cik varchar(10) not null,
    company_name varchar(255) not null,
    form varchar(32) not null,
    filing_date date,
    accession_number varchar(64) not null,
    primary_document varchar(512),
    filing_url varchar(2048) not null,
    signal_type varchar(64),
    signal_reason varchar(1024),
    processed_at timestamp with time zone not null
);

alter table sec_filings
    add constraint uk_sec_filings_accession unique (accession_number);

create index idx_sec_filings_filing_date
    on sec_filings (filing_date desc, processed_at desc);

create index idx_sec_filings_cik
    on sec_filings (cik);
