create table sec_watchlist_companies (
    id bigint generated by default as identity primary key,
    cik varchar(10) not null,
    company_name varchar(255) not null,
    ticker varchar(32),
    notes varchar(1024),
    enabled boolean not null default true,
    created_at timestamp with time zone not null,
    updated_at timestamp with time zone not null
);

alter table sec_watchlist_companies
    add constraint uk_sec_watchlist_companies_cik unique (cik);

create index idx_sec_watchlist_companies_enabled
    on sec_watchlist_companies (enabled);
