create table deal_group_reviews (
    id bigint generated by default as identity primary key,
    group_key varchar(512) not null unique,
    manual_review_status varchar(32) not null,
    manual_review_reason varchar(64),
    manual_review_note varchar(2048),
    manual_reviewed_at timestamp with time zone,
    created_at timestamp with time zone not null,
    updated_at timestamp with time zone not null
);
