create table deal_group_ai_reviews (
    id bigint generated by default as identity primary key,
    group_key varchar(512) not null,
    model varchar(128) not null,
    verdict varchar(64) not null,
    confidence varchar(16) not null,
    tradable_public_target boolean,
    suggested_review_status varchar(32),
    suggested_review_reason varchar(64),
    reason varchar(4000),
    risk_flags varchar(2048),
    raw_json varchar(10000),
    created_at timestamp with time zone not null
);

create index idx_deal_group_ai_reviews_group_key_created_at
    on deal_group_ai_reviews (group_key, created_at desc);
